### ISSUE TITLE
Perpetuall (free of any kind of ads) is considered as an app with adds and its connections are cancelled

### ISSUE THREAD

**Issue by cpolo** [dschuermann/ad-away#593]
Perpetuall (free of any kind of ads) is considered as an app with adds and its connections are cancelled.
It is generating a lots of problems in our users.
We are using parse.com servers and we think that that is the reason for you to consider our app as an Ad app.

Please considerer improving your app to solve this big issue.

Thanks.

**Comment by stonerl** [comment]
Well, the problem is not the app. It is the blocklists your users use. So if parse.com is part of their block list the developer can't do anything to fix this. Your users should consider whitelisting this specific host.

**Comment by cpolo** [comment]
Thanks Tony for the response.

The point is that inside parse.com, there are hundreds of apps, some of
them use ads, some other not. Is not really a matter of whitelisting an IP,
is something more related on how you block apps / sites.

Anyhow, thanks for your response.

Regards,


On Tue, Jan 20, 2015 at 12:41 PM, Toni Förster <notifications@github.com>
wrote:

> Well, the problem is not the app. It is the blocklists your users use. So
> if parse.com is part of their block list the developer can't do anything
> to fix this. Your users should consider whitelisting this specific host.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dschuermann/ad-away/issues/593#issuecomment-70641598>.
>



-- 

*Carlos Polo*

Your contacts always updated
Descarga la app aquí: get.perpetuall.net

Mobile: +34 607 811 804
Phone: +34 94 476 28 77
Skype: carlospologil

**Comment by dschuermann** [comment]
@cpolo Contact the maintainer of the hosts file that contain parse.com . See https://github.com/dschuermann/ad-away/wiki/HostsSources#adaways-default-hosts-sources
