### ISSUE TITLE
update externals

### ISSUE THREAD

**Issue by 0-kaladin** [dschuermann/ad-away#599]
i've updated tcpdump, dnsmasq, libpcap and also mongoose.
I have my rough work here: https://github.com/0-kaladin/ad-away/commits/update_externals
Was going to clean it up and submit pull request but not sure if you are interested. As
1. I don't know of a real reason to update these outside of it just might be a good idea.
2. after all compiled the binary size went from 3.3mb to about 3.8mb.
3. I haven't been able to see any net gain by doing this, there is much that is updated bug, security, feature wise in all these but maybe not applicable to ad-aways limited use of them.
I pulled the updates for tcpdump, dnsmasq, libpcap direct from google source:
https://android.googlesource.com/platform/external/tcpdump

then if you look at my commits I did what was needed to get it to complile within adaway.

**Comment by 0-kaladin** [comment]
oh never pushed up the mongoose... the last commit here is the mongoose update to the latest from their source.
https://github.com/0-kaladin/ad-away/tree/mongoose

**Comment by dschuermann** [comment]
Definitely a good idea to update all externals for fixing security holes. Please do a pull request for your work. Much appreciated!

**Comment by 0-kaladin** [comment]
Posted the pull request https://github.com/dschuermann/ad-away/pull/600
